controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml
app_blog:
    path: /blog
    controller: App\Controller\BlogController::index

# config/routes.yaml
app_home:
    path: /
    controller: App\Controller\BlogController::index
# config/routes.yaml
app_home:
    path: /
    redirect: /blog
# config/routes.yaml

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
# config/routes.yaml

create_article:
    path: /create-article
    controller: App\Controller\ArticleController::createArticle
